# Generated by Django 3.2.2 on 2021-05-11 10:17

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20210511_0951'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('end__gt', django.db.models.expressions.F('start'))), name="Event's 8h time limit"),
        ),
    ]
