# Generated by Django 3.2.2 on 2021-05-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', "0007_event_event's 8h time limit"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name="Event's 8h time limit",
        ),
    ]
