# Generated by Django 3.2.2 on 2021-05-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210512_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('M', 'Manager'), ('O', 'Owner'), ('P', 'Participant'), ('A', 'Administrator')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
