# Generated by Django 3.2.2 on 2021-05-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Owner', 'Owner'), ('Participant', 'Participant')], max_length=20),
        ),
    ]
