# Generated by Django 3.2.2 on 2021-05-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role_name',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Owner', 'Owner'), ('Participant', 'Participant'), ('Administrator', 'Administrator')], default='asdf', max_length=20),
            preserve_default=False,
        ),
    ]
