# Generated by Django 3.2.2 on 2021-05-13 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210512_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='profile',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role_name',
            field=models.CharField(choices=[('Participant', 'Participant'), ('Owner', 'Owner'), ('Administrator', 'Administrator'), ('Manager', 'Manager')], max_length=20),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
